---
title: "**Title**: Linking pinyon jay population abundance to pinyon cone production and climate in the SW United States"
format:
  docx:
    reference-doc: custom-reference-doc.docx
editor: visual
bibliography: references.bib
csl: journal-of-animal-ecology.csl
---

**Author list**: Ana Miller-ter Kuile^1,2^, Andreas Wion^3^, Kyle Rodman^4^, Kiona Ogle^1^, Jamie S. Sanderlin^2^

**Author affiliations**:

1 Northern Arizona University School of Informatics, Computing, and Cyber Systems, Flagstaff, Arizona, USA

2 USDA Forest Service Rocky Mountain Research Station, Flagstaff, Arizona, USA

3 USGS Santa Fe, New Mexico, USA

4 Ecological Restoration Institute, Northern Arizona University, Flagstaff, Arizona, USA

**Keywords**:

# Data availability

\newpage

# Abstract

# 1 Introduction

What happens to mutualisms across time and space and ongoing directional change?

\[big picture\]

Mutualist relationships have co-evolved and may be changing with climate change. Additionally, how we may draw understanding about the diversity of responses because these mutualist relationships occur on the background of other broad-scale variation in species' ranges that might mediate (good or bad, helping/hurting) the co-evolution and its response to global change drivers.

\[zooming in\]

In the SW, there is an important mutualism between pinyon pine and pinyon jays. Jays have been declining over the last several decades. This jay caches pinyon seeds across the landscape to eat or to forget later and help the tree disperse to new areas. Pinyon pines have also seen dramatic shifts in range (expansions, die offs) and reproduction due to climate change and climate variability. \[Some biology about pinyon masting. Some more info on the nature of the co-evolution here too\]

\[gap\]

\[What is causing their decline?\] Given the complex co-evolution of the interaction between the pinyon pine and the pinyon jay, it is hard to tease apart the cause and effect of these patterns or how changes in resource availability alter jay abundances. This has not been evaluated to date. It is likely that, given the broad geographical range of both species, that a different combination of forces may be playing out across the species' range, and that these effects may not be concurrent. Pinyon pine cone production occurs \~2 years following favorable climate years. Other food resources for jays in these systems may respond more quickly to the same climate conditions (e.g., insects, junipers, and gambel oak). Thus, it may be that jay populations increase \*prior\* to good cone years for pinyon pines as they are either signaled to "get ready" by the same climate conditions as trees or because their populations get a boost prior to a good cone year from other food resources. The result of jays "predicting" good cone years is that more jays will be in the landscape to distribute seeds to more new places. In addition or conversely, jays could also respond with an immediate or lagged effect to cone production as seed resources give them immediate or lagged benefits to survival, fitness, and reproduction. Teasing these patterns out and how other climatic conditions mediate these effects could be imperative for understanding the link between patterns in resources and birds and help in conservation of the species.

\[our study\]

In this study, we aimed to determine the relationship between pinyon pine cones and pinyon jay abundance in the Southwest US and how other site-level factors may mediate this relationship. To leverage the broadest spatial and temporal availability of data on pinyon jay abundance, we used eBIRD (Cite) data from (2010 - 2021) to evaluate how pinyon jay abundance is related to cone production (CITE andreas), pinyon pine basal area, climate (maximum temperature, precipitation, and monsoonality), and the interactions between cone production and these other variables as broad-scale mediators of the relationship between cone availability and alternative food sources in a given site and a given year (e.g., seeds, acorns, insects). We allowed cone availability to have immediate, lead (jays "predict" cone years), and lag (jays "respond to" cone years) effects on jay abundance using a stochastic antecedent modeling approach (CITE). Relatedly, we allowed maximum temperature and precipitation to have lagged and immediate effects on jay abundance. Specifically, in this study, we wanted to evaluate 1) how strong is the relationship between pinyon jay abundance and cone availability? and 2) how is this relationship mediated by habitat and climate variables that vary by site and/or year? This study provides a valuable way of determining the strength of co-evolution between pinyon pines and pinyon jays and valuable insights into the broad-scale mechanisms by which pines and jays may be declining in the Southwest US with key insights for conservation of both species.

# 2 Methods

### 2.1 Pinyon jay biology and study site

Pinyon jays are a widespread species that occurs across the western US (California, Nevada, Utah, Arizona, Colorado, New Mexico). Pinyon jays are generalist seed- and insect-eaters and are part of an important mutualistic relationship with pinyon pines (CITE Balda 2020, Ligon 1978). Birds cache large amounts of pinyon pine seeds when they are available and by burying seeds they increase the potential for seedlings to germinate (CITE: Floyd 1982). Pinyon jays often flock and nest in large numbers and are highly social \[maybe examples\] (CITE some behavior studies). Pinyon jays are in decline across much of their rangefor a variety of potential reasons, including changes in habitat quality and food availability (CITE Boone, VanLannen). Concurrently, pinyon pines have seen shifts in their range and reproduction \[Andreas - provide some details here about decline/change for pinyon pine\].

Although pinyon jays occur across the western US, in this study, we focused on the intermountain and southwest regions of the US because of available information on cone production (e.g., data from Utah, Colorado, New Mexico, and Arizona; CITE ANDREAS). \[Any other justifications for including only data from this region WRT climate/habitat? Please add tree guys\].

### 2.2 Covariate data

Because we are interested in relationships between pinyon jays and pinyon pine cone production, we built a model that included cone production (CITE Wion et al. 2025) and other mediating factors. These mediating factors included site-level yearly climate and pinyon basal area data as well as site level average monsoonal moisture (precipitation occurring in July and August). We compiled all covariates at a 4x4 km raster grid scale since this is a scale at which these data are available (e.g., PRISM). Cone production data came from published models estimating yearly cone production across the region \[Andreas, please fill in here\]. We derived yearly basal area by \[Kyle please fill in here\]. In addition to these covariates, we also gathered gridded climate data relevant to bird biology (physiology and alternative food availability; CITE stuff here) from PRISM, including monthly maximum temperature, monthly cumulative precipitation, and the percent of the 30-year monthly normal precipitation falling in the months of July and August to quantify the proportion of moisture experienced in a grid during the monsoon season (CITE something about monsoon).

### 2.3 eBIRD filtering and subsampling

To estimate pinyon jay abundance in relation to recent (2010-2021) cone abundance, we used data from eBIRD \[cite\] data from the four states of interest (Arizona, Colorado, New Mexico, and Utah) and further filtered pinyon jay observations to areas with pinyon pine vegetation cover (CITE where Kyle got his pinyon pine layers from). We chose to use eBIRD data because it has broad spatial and temporal coverage within the region of interest and fine enough spatial scale to compare bird abundance at a scale similar to that of our covariates (4 x 4 km grid cells). This scale is too fine for many broad-scale standardized monitoring protocols, such as Breeding Bird Survey (25-mile transects; CITE).

eBIRD is community science data, meaning that non-scientist birders collect eBIRD data and contribute to the eBIRD database. We followed filtering methods from the eBIRD database curators (Cornell Lab CITE/LINK HERE). Specifically, we selected data that represented only complete checklists (e.g., observers recorded all birds of all species observed, not just individuals of species of interest). We selected checklists from the nesting season (late February to early May CITE) and included only observations of "stationary" and "traveling" protocols. We considered only the nesting season because this is a time of year in which the mechanisms for local bird abundance are easy to evaluate because of communal nesting behavior and because nesting often occurs near areas where birds have cached seeds from the previous year (CITE). We only included checklists that were collected in under five hours, 0-5 km in distance, and with ten or fewer observers.

eBIRD data is unstructured data without a regular sampling design, so we performed spatial and temporal sub-sampling [@robinson2018]. To do this, we divided the landscape into 4x4 km grid cells to match the spatial scale of the covariates. We spatially sub-sampled eBIRD observations to include a set of checklists in each grid cell that represented relatively equal sampling effort across time and space. Given that we observed the fewest number of checklists per year in 2010 (4.2 checklists per grid cell), we subsampled to this level (4 checklists per cell). After filtering to this level, we still had fewer checklists in early years due to fewer cells having checklists in them. Thus, we further reduced temporal bias by subsampling checklists again so that we had relatively equal sample sizes across years based on the year with the fewest checklists (n = 1715 checklists in 2010). We performed this temporal sampling randomly (e.g., not by 4x4 km grid cell) We also removed all checklists within 10 km of the exterior edges of the four states for which we had data (Arizona, Colorado, New Mexico, and Utah) since we had masked some other covariate layers to these states and observations near edges may have misrepresented values for pinyon basal area and cone production. As a result, we had, on average \_\_ checklists per grid cell in a specific year.

### 2.5 Modeling relationships between cones and birds with eBIRD

To explore relationships between pinyon jay abundance and environmental covariates, we used a two-part model with an observation process for eBIRD and a biological process model that estimates latent "abundance" values (CITE). The observation process models include covariates that describe variation in detection probabilities (e.g., survey conditions). The biological process includes a likelihood that describes the biological drivers of latent abundance. These covariates include a stochastic antecedent modeling structure that allows cone abundance to have both lead and lagged effects (e.g., bird abundance can respond before or after cone maturation) and other yearly climate variables to have lagged effects [@ogle2015].

### 2.4.1 Observation process for eBIRD

In our two-part model, observed count data from eBIRD checklists are used to estimate a "true" latent abundance, $N$, which is dependent on space and time (more in section NAME). eBIRD data are provided in an observation process models that incorporates covariates that impact the detection of birds. Observed count data are binomially distributed based on a detection probability for a checklist in a year and the "true" latent abundance for the space and time in which those checklists occur, $N$, being the total possible "trials".

eBIRD checklists are recorded with a geographical point location and also often include observers walking some distance (\< 5km in our dataset after filtering). Thus, there is spatial uncertainty arising from two sources: 1) uncertainty in the location in which the survey was conducted (e.g., was the location recorded at the beginning, middle, or end of a survey and at what level of precision) and 2) uncertainty in the location along a survey at which pinyon jays were observed (e.g., were birds observed at the beginning, middle, or end of a walking survey). To account for this spatial uncertainty, we created buffers around each eBIRD checklist based on the sampling distance for that checklist (1/2 of distance traveled for "traveling" checklists; 0.5 km for "stationary" checklists). Then, we created a merged polygon ("blob") of all the checklists within a 4x4 grid cell in a given year by merging the buffers of all checklists within a grid cell. Thus, the "blob" and not the underlying 4x4 km grid cell, is the spatial unit at which we estimated abundance, *N*.

eBIRD observed count data for checklist, $c$, in blob, $i$, and year, $y$, are binomially distributed based on a detection probability, *p*, and the latent true abundance of birds in the blob in which the checklist is located:

$$
eBIRDCount_{c,i,y} \sim Binomial(N_{i,y}, p_{c,i,y})
$$

The detection probability for eBIRD data includes a regression with the detection covariates of survey type (stationary or traveling), start time, duration of survey, distance traveled, and the number of observers for each checklist. See above (\_\_\_) for how we filtered these variables initially based on best practices so that checklists represented similar effort. These covariates all depended on checklist, blob, and year. Thus, the detection component of the model has a likelihood of the form:

$$
logit(p_{c,i,y}) = \gamma_0 + \sum_{j=1}^{5}\gamma_j\cdot X_{j_{c,i,y}}
$$

where $\gamma_0$ is the underlying detection probability (intercept) and each $\gamma_j$ is the slope of the relationship between detection probability (on the logit scale) and a set of *J* covariates (j = 1, 2, ... 5).

### 2.4.2 Biological process of latent pinyon jay abundance with covariates with lead and lagged effects

Latent true abundance of jays in a blob in a year, $N_{i,y}$ is Poisson distributed around an expected rate parameter, $\lambda_{i,y}$, multiplied by the area of the blob, $A_{i}$ as follows:

$$
N_{i,y} \sim Poisson(\lambda_{i,y}\times A_i)
$$

Furthermore, $\lambda_{i,y}$ is dependent on a regression of environmental covariates:

$$
log(\lambda_{i,y}) = \alpha_0 + \sum_{j=1}^J \alpha_j \cdot X_{j_{i,y}} + \sum_{k=1}^K \alpha_k \cdot Z_{k_{i,y}} + \sum_{m=1}^4\sum_{n=m+1}^4 \alpha_{mn} \cdot Z_{m_{i,y}} \cdot X/Z_{n_{i,y}}
$$

In this formulation, covariates $X_{j_{i,y}}$ include only concurrent effects. These variables in the model include monsoonality and pinyon pine basal area (yearly). Conversely, values for each $Z_{k_{i,y}}$ comprise a stochastic antecedent structure [@ogle2015] dependent on the covariate, where each $Z_{k_{i,y}}$ is the weighted average value of a set of seasonal or yearly values for that covariate across a defined set of seasons or years. The weights for each covariate across all seasons or years, *l*, $w_{k,l}$, have a Dirichlet prior and sum to 1. The weight, or importance weight, for each season or year indicates how important that value is to the overall effect (larger values of the weight mean more importance of that season or year to that covariate effect). The covariates for which antecedent weights are calculated are cone production, maximum temperature, and precipitation. Cone production is considered on a yearly scale (cones only produce up to one time in a year) and include both lead and lagged effects (e.g., jays "predict" cone years or "respond" to good cone years), and include three prior years, the current year, and three years after the current year. Both temperature and precipitation are at a seasonal scale and only consider lagged effects. The seasons are based on important seasonal biology for pinyon jays, including: breeding (February-April), feeding dependent young (May-June), summer (July), fall and winter foraging, potentially with irruption (August - January) [@wigginsd.a.2005]. For seasonal covariates, we considered 12 seasons into the past. We also considered interactions between cone production and all other covariates (pinyon basal area, monsoonality, maximum temperature, and precipitation) to determine how the relationship between cones and birds is mediated by other covariates related to cone reliability and alternative food resources (e.g., juniper berries, acorns, insects).

Because blobs sometimes covered more than one 4x4 km grid cell (average value and range here\_\_\_), we determined the percent of a blob covering each of these grid cells and then calculated weighted average covariate values based on the covariate values of all overlapped cells times the percent of the blob overlapping that cell. On average, blobs covered \_\_ 4x 4 km grid cells, with a minimum of one grid and a maximum of \_\_ for a single blob.

| Covariate or interaction           | Description                                                                                                                   | Question                                                                                                                          |
|----------------|----------------------------|-----------------------------|
| Pinyon pine cone abundance         | Abundance of cones from a predictive model (CITE)                                                                             | How is pinyon jay abundance linked to pinyon cone availability (can have lead, immediate, and lagged effects)?                    |
| Maximum temperature                | A proxy for physiological limits and/or insect resource availability (can have lagged effects)                                | How is pinyon jay abundance linked to physiological limits and/or insect availability?                                            |
| Cumulative precipitation           | A proxy for insect resource availability (can have lagged effects)                                                            | How is pinyon jay abundance linked to insect availability?                                                                        |
| Monsoonality                       | The degree to which the site depends on monsoon moisture (percent of total annual precipitation occurring in July and August) | How is pinyon jay abundance shaped by broad-scale climatic mediators of cone reliability?                                         |
| Pinyon basal area                  | The basal area of pinyon pine                                                                                                 | How is pinyon jay abundance shaped by local habitat preferences for food trees?                                                   |
| Cone abundance x Temperature       |                                                                                                                               | Is the importance of cone abundance for jays mediated by temperature?                                                             |
| Cone abundance x Precipiation      |                                                                                                                               | Is the importance of cone abundance for jays mediated by precipitation (e.g., more/less availability of insect prey)              |
| Cone abundance x Monsoonality      |                                                                                                                               | Is the importance of cone abundance for jays different across a range of monsoonal conditions that alter cone reliability?        |
| Cone abundance x Pinyon basal area |                                                                                                                               | Is the importance of cone abundance for jays different depending on the local habitat configuration and abundance of pinyon pine? |

### 2.5 Model implementation, convergence, and diagnostics

We implemented models in the Bayesian software JAGS (CITE) using R (CITE) and the jagsUI wrapper package (CITE). We prepared data using the here (CITE), tidyverse (CITE), sf (CITE), terra (CITE), readxl (CITE), exactextractr (CITE), spatialEco (CITE), nngeo (CITE), sp (CITE), auk (CITE), lubridate (CITE), prism (CITE), and data.table (CITE) packages.

We initially ran models to generate 4000 MCMC samples with which to determine how many iterations would be needed to reach convergence (CITE). We then re-ran models with more iterations and initial values sufficient to reach convergence based on the raftery.diag() function in the coda package (CITE). We assessed model convergence by evaluating trace, history, and autocorrelation plots generated with the mcmcplots package (). We quantified model convergence by evaluating whether Gelman-Ruman statistics, $\hat{R}$, for all root nodes in the model were \< 1.1 (CITE). We assessed model goodness-of-fit by comparing observed count data from eBIRD to predicted count data based on the model mean value. We verified the lack of spatial autocorrelation in observed data by examining the residuals using \[give methods here SI Figure X\].

# Results

# Discussion

# Tables and Figures

# References

```{r}
#| echo: false
#| eval: false
#| include: false

#found info on adding reference styles here:
#https://quarto.org/docs/authoring/citations.html
#and list of csls here:
#https://www.zotero.org/styles

```

# 
